### ISSUE TITLE
Fix `useRequestUrl` returning `localhost` on production environment

### ISSUE THREAD

**Issue by stefanobartoletti** [stefanobartoletti/nuxt-social-share#177]
Using `useRequestUrl` composable is returning `localhost` on some production environments.

According to the docs here https://nuxt.com/docs/api/composables/use-request-url it is a known behavior, caused by Nitro caching features.

Currently, this is happening regardless of the hosting platform, i.e. both the playground of this module here, hosted on GitHub Pages:

- https://stefanobartoletti.github.io/nuxt-social-share/

and a live website here, on Netlify:

- https://nuxt-storyblok-starter.netlify.app/blog/article-8/ (here it is happening only if accessed directly, if navigating from another page on the site, the URL seems correct)

If possible, some configuration to be placed here in the module is desirable, to avoid setting this up in every project that uses the module.

Some help and clarifications have been asked here https://github.com/nuxt/nuxt/discussions/27393

**Comment by letoast** [comment]
The facebook issue https://github.com/stefanobartoletti/nuxt-social-share/issues/175 seems to be more than just localhost being provided by in the URL. You can see here that the URL is actually correct, but the facebook share still doesn't work correctly. The other platforms seem to work.
![image](https://github.com/stefanobartoletti/nuxt-social-share/assets/8151795/44f4bfcc-0a2d-4a7a-a412-8803d4a5b41f)

![image](https://github.com/stefanobartoletti/nuxt-social-share/assets/8151795/05ef44ff-e966-4634-9f73-4d3c94bd4d76)

**Comment by stefanobartoletti** [comment]
Thanks for reporting, apparently it is a problem on Facebook side, either they changed the behavior of the URL or they have some issues. Besides trying to stay updated about this, there is not much I can do on the module at the moment I fear.

**Comment by stefanobartoletti** [comment]
The bug returning `localhost` has been fixed in the latest `v1.0.0` release.

@letoast @junogueira The issue with Facebook is not 100% related to this, and it seems to be related to external factors and not always reproducible. If the issue persists, and if it can be solved on the module, another specific issue can be opened.
