### ISSUE TITLE
[Feature]: dynamic baseURL from `useRequestEvent` (server) or `location` (client)

### ISSUE THREAD

**Issue by Hrdtr** [stefanobartoletti/nuxt-social-share#209]
### Please take a moment to familiarize yourself with this project scope and standards

- [X] I have read the [Documentation](https://github.com/stefanobartoletti/nuxt-social-share?tab=readme-ov-file) and I understand how to correctly use this module.
- [X] I have read the [Contributing Guidelines](https://github.com/stefanobartoletti/nuxt-social-share/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/stefanobartoletti/nuxt-social-share?tab=coc-ov-file)

### Describe your idea

This is useful for dynamic host app (for example multi-tenancy app)
Also, the last breaking changes isn't really needed if it just used for constructing shareUrl since we can get the current baseURL using `useRequestEvent` composable.

### Contribution

- [X] I am willing to contribute to the implementation of this feature.

**Comment by stefanobartoletti** [comment]
It is not that clear what you are asking or proposing here.

Would you elaborate more about the underlying issue, use cases, and proposed solution?

**Comment by Hrdtr** [comment]
I'm currently working on a saas project, each tenant have its own subdomain, so I need to make the baseURL config dynamic.
Of course we can override the config at runtime using plugin, but I think the main reason why I opened this issue is because it isn't necessary to make the baseURL config required since it can be retrieved dynamically. But again it's up to you
You can freely close this issue and related pr if it doesn't match your mind. And maybe just wanted to document about multi-host / dynamic baseURL use-case

**Comment by stefanobartoletti** [comment]
Have you considered using environment variables to provide each site's URL into Nuxt config?

**Comment by Hrdtr** [comment]
Every user can use any available subdomain, so this is not a static config.
Actually, there are many ways to solve this kind of problem
We can override env value, override nuxt.config value on runtime, or just pass full url target when using this module
But again, this is not the main reason of why I opened this issue
> the main reason why I opened this issue is because it isn't necessary to make the baseURL config required since it can be retrieved dynamically

Maybe I just don't know any other reasons for making the baseURL config required? Other than to construct URL object of the share target

**Comment by stefanobartoletti** [comment]
The baseURL config item is used only to build the URL, but I don't see the need right now to change this behavior if it is not causing problems or limiting the functionality.

I tried before to have a dynamic URL but I was having some issues (admittedly, with a different approach than what you are proposing), but in the end, the current solution is the most straightforward and the one that requires the less implemented logic.

While I appreciate your efforts, if your solution is not helping in fixing some problems, the current config-based implementation has the least code logic and imports fewer builtin functions, in turn making it more efficient from a maintenance point of view and more future-proof.

Maybe I'm missing something, would your solution work better in some contexts that I have not considered?

**Comment by Hrdtr** [comment]
My idea just to make this module usage straightforward, just like previous versions behavior by omitting the required base URL config. It is not really causing a problem in general. But only if you include guidances inside the documentation about how to handle dynamic baseURL

Can you share what kind of issue you have while having a dynamic base url approach?

**Comment by stefanobartoletti** [comment]
The documentation already has a note in the options description stating that `baseURL` can be provided by an environment variable, I suppose I can probably consider giving it more emphasis.

But I don't see the requirement of having some mandatory configuration options to be a huge problem, since almost all modules behave like this (and, i.e., Nuxt Seo also has a similar config option to set the base URL of the site), and the feature is documented. 

The issue was related to `useRequestURL` and it was described in #177 

Generally speaking, I tend to favor choices that lead to more simplicity: I prefer a config option over making the codebase more complex by adding more logic and using more builtin functions that can (now or in the future) bring undesired side-effects like the linked issue.

**Comment by l-besenyei** [comment]
Im working on a multilingual site using `@nuxtjs/i18n`, each language has its own domain, so using a single baseUrl config will not work for my case.

This solution should work but, @stefanobartoletti, have you considered enabling support for i18n?

**Comment by stefanobartoletti** [comment]
@l-besenyei would using an environment variable not be enough in your setup? Could you test it and report back?
