### ISSUE TITLE
[Bug]: Line not working

### ISSUE THREAD

**Issue by MilesWuCode** [stefanobartoletti/nuxt-social-share#236]
### Please take a moment to familiarize yourself with this project scope and standards

- [X] I have read the [Documentation](https://github.com/stefanobartoletti/nuxt-social-share?tab=readme-ov-file) and I understand how to correctly use this module.
- [X] I have read the [Contributing Guidelines](https://github.com/stefanobartoletti/nuxt-social-share/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/stefanobartoletti/nuxt-social-share?tab=coc-ov-file)

### Environment

```shell
Nuxt3
```

### Minimal reproduction link

no

### Describe the bug/issue

line's link redirect to line's official web

https://developers.line.biz/en/docs/line-social-plugins/install-guide/using-line-share-buttons/#using-custom-icons

https://social-plugins.line.me/lineit/share?url=${url}

**Comment by stefanobartoletti** [comment]
@MilesWuCode fixed in the latest release
